spring:
  application:
    name: pamapay

  datasource:
    url: jdbc:postgresql://localhost:5433/pamapay?options=-c%20TimeZone=Asia/Kolkata
    username: pamapay_user
    password: 8933
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret:${JWT_SECRET}
    expiration:${JWT_EXPIRATION:3600000}

server:
  port: 8080